### ISSUE TITLE
Callback events

### ISSUE THREAD

**Issue by oscarstranger** [Elkfox/Customer#3]
Would be awesome to add some callback events so that external functions using `customer.js` can watch for when the customer data has been updated etc. For Alldock, I manually added in my own function call to the Freegeo ajax success event, but obviously the idea would be to not have to mess with the core js to plug in other external functions.

You can see the reference to the `concrete.region` function below:

```
jQuery.ajax({
  url: '//freegeoip.net/json/',
    type: 'POST',
    dataType: 'jsonp',
    success: function(location) {
      this2.update(location)
      concrete.region.check();
  }
})
```

**Comment by ButsAndCats** [comment]
Added both callback functions and jQuery events.

**Comment by ButsAndCats** [comment]
Have updated the docs too
